name: Update Languages Table

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-langs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Run update_langs
        env:
          REPO: Aniket-Mishra/dotfiles
          README_PATH: ${{ github.workspace }}/README.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo run --release --manifest-path rust_tools/update_langs/Cargo.toml

      - name: Commit changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update language stats" || echo "No changes"
          git push
